apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: appgo

images:
- name: 0xdutra/argo-appgo
  newName: 0xdutra/argo-appgo
  newTag: 6f6628f35b755283a8aa0c04649bac61a783882b
