apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: appgo

images:
- name: 0xdutra/argo-appgo
  newName: 0xdutra/argo-appgo
  newTag: 1f535b6153f25ac5e1546f4ccee9e9f02ffc3c79
